services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iob_dev
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ./iob-api
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:postgres@db:5432/iob_dev
      DEVISE_JWT_SECRET: changeme-please
      FRONTEND_ORIGIN: http://localhost:5173
    volumes:
      - ./iob-api:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    user: "${UID}:${GID}"
    command: >
      bash -lc "rm -f tmp/pids/server.pid &&
      bundle install &&
      bin/rails db:prepare &&
      exec bin/rails s -b 0.0.0.0 -p 3000"

volumes:
  db-data:
